# Generated by Django 5.2.7 on 2025-11-04 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('oficinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BienPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_patrimonial', models.CharField(help_text='Código único del bien patrimonial', max_length=50, unique=True, verbose_name='Código Patrimonial')),
                ('codigo_interno', models.CharField(blank=True, help_text='Código interno de la institución', max_length=50, verbose_name='Código Interno')),
                ('estado_bien', models.CharField(choices=[('N', 'Nuevo'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('E', 'RAEE'), ('C', 'Chatarra')], default='B', help_text='Estado de conservación del bien', max_length=1, verbose_name='Estado del Bien')),
                ('marca', models.CharField(blank=True, help_text='Marca del bien', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, help_text='Modelo del bien', max_length=100, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, help_text='Color del bien', max_length=50, verbose_name='Color')),
                ('serie', models.CharField(blank=True, help_text='Número de serie del bien', max_length=100, verbose_name='Serie')),
                ('dimension', models.CharField(blank=True, help_text='Dimensiones del bien', max_length=100, verbose_name='Dimensión')),
                ('placa', models.CharField(blank=True, help_text='Placa del vehículo', max_length=20, verbose_name='Placa')),
                ('matricula', models.CharField(blank=True, help_text='Matrícula del vehículo', max_length=20, verbose_name='Matrícula')),
                ('nro_motor', models.CharField(blank=True, help_text='Número de motor del vehículo', max_length=50, verbose_name='Número de Motor')),
                ('nro_chasis', models.CharField(blank=True, help_text='Número de chasis del vehículo', max_length=50, verbose_name='Número de Chasis')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el bien', verbose_name='Observaciones')),
                ('qr_code', models.CharField(blank=True, help_text='Código QR único del bien', max_length=200, unique=True, verbose_name='Código QR')),
                ('url_qr', models.URLField(blank=True, help_text='URL única para acceso mediante QR', verbose_name='URL QR')),
                ('fecha_adquisicion', models.DateField(blank=True, help_text='Fecha de adquisición del bien', null=True, verbose_name='Fecha de Adquisición')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de adquisición en soles', max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('catalogo', models.ForeignKey(help_text='Denominación del bien según catálogo oficial', on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogo', verbose_name='Catálogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(help_text='Oficina donde se encuentra ubicado el bien', on_delete=django.db.models.deletion.PROTECT, to='oficinas.oficina', verbose_name='Oficina')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien Patrimonial',
                'verbose_name_plural': 'Bienes Patrimoniales',
                'ordering': ['codigo_patrimonial'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado_anterior', models.CharField(choices=[('N', 'Nuevo'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('E', 'RAEE'), ('C', 'Chatarra')], max_length=1, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('N', 'Nuevo'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('E', 'RAEE'), ('C', 'Chatarra')], max_length=1, verbose_name='Estado Nuevo')),
                ('observaciones', models.TextField(blank=True, help_text='Justificación del cambio de estado', verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('ubicacion_gps', models.CharField(blank=True, help_text='Coordenadas GPS del cambio (desde móvil)', max_length=100, verbose_name='Ubicación GPS')),
                ('foto', models.ImageField(blank=True, help_text='Foto del bien en el momento del cambio', upload_to='estados/', verbose_name='Foto')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.bienpatrimonial', verbose_name='Bien')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(help_text='Motivo del movimiento', max_length=200, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del movimiento', verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('confirmado', models.BooleanField(default=False, help_text='Indica si el movimiento ha sido confirmado', verbose_name='Confirmado')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('bien', models.ForeignKey(help_text='Bien que se está moviendo', on_delete=django.db.models.deletion.CASCADE, to='bienes.bienpatrimonial', verbose_name='Bien')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('oficina_destino', models.ForeignKey(help_text='Oficina de destino del movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='oficinas.oficina', verbose_name='Oficina Destino')),
                ('oficina_origen', models.ForeignKey(help_text='Oficina de origen del movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='oficinas.oficina', verbose_name='Oficina Origen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Bien',
                'verbose_name_plural': 'Movimientos de Bienes',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['codigo_patrimonial'], name='bienes_bien_codigo__0e0f62_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['qr_code'], name='bienes_bien_qr_code_cc4e97_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['estado_bien'], name='bienes_bien_estado__dded3a_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['catalogo'], name='bienes_bien_catalog_de597e_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['oficina'], name='bienes_bien_oficina_64bf56_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['placa'], name='bienes_bien_placa_d80b61_idx'),
        ),
        migrations.AddIndex(
            model_name='bienpatrimonial',
            index=models.Index(fields=['serie'], name='bienes_bien_serie_82f4fb_idx'),
        ),
    ]
