# Generated by Django 5.2.7 on 2025-11-03 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREAR', 'Crear Bien'), ('ACTUALIZAR', 'Actualizar Bien'), ('CAMBIAR_ESTADO', 'Cambiar Estado'), ('AGREGAR_FOTO', 'Agregar Foto'), ('INVENTARIO', 'Registro de Inventario')], max_length=20)),
                ('timestamp_local', models.DateTimeField()),
                ('timestamp_servidor', models.DateTimeField(auto_now_add=True)),
                ('bien_codigo_patrimonial', models.CharField(blank=True, max_length=50)),
                ('bien_qr_code', models.CharField(blank=True, max_length=200)),
                ('datos_cambio', models.JSONField()),
                ('estado_sync', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('CONFLICTO', 'Conflicto')], default='PENDIENTE', max_length=20)),
                ('intentos_sync', models.IntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=100)),
                ('ubicacion_gps', models.CharField(blank=True, max_length=100)),
                ('conflicto_resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflictos_resueltos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_local'],
            },
        ),
        migrations.CreateModel(
            name='ConflictoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conflicto', models.CharField(choices=[('BIEN_MODIFICADO', 'Bien modificado en servidor'), ('BIEN_ELIMINADO', 'Bien eliminado en servidor'), ('CODIGO_DUPLICADO', 'Código patrimonial duplicado'), ('DATOS_INCONSISTENTES', 'Datos inconsistentes')], max_length=30)),
                ('datos_servidor', models.JSONField()),
                ('datos_cliente', models.JSONField()),
                ('resuelto', models.BooleanField(default=False)),
                ('resolucion_elegida', models.CharField(blank=True, choices=[('SERVIDOR', 'Mantener datos del servidor'), ('CLIENTE', 'Aplicar datos del cliente'), ('MANUAL', 'Resolución manual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambio_offline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobile.cambiooffline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(max_length=100)),
                ('inicio_sync', models.DateTimeField(auto_now_add=True)),
                ('fin_sync', models.DateTimeField(blank=True, null=True)),
                ('cambios_pendientes', models.IntegerField(default=0)),
                ('cambios_procesados', models.IntegerField(default=0)),
                ('cambios_exitosos', models.IntegerField(default=0)),
                ('cambios_con_error', models.IntegerField(default=0)),
                ('cambios_con_conflicto', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('mensaje_resultado', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio_sync'],
            },
        ),
        migrations.AddIndex(
            model_name='cambiooffline',
            index=models.Index(fields=['usuario', 'estado_sync'], name='mobile_camb_usuario_d13f37_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiooffline',
            index=models.Index(fields=['bien_codigo_patrimonial'], name='mobile_camb_bien_co_a76c86_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiooffline',
            index=models.Index(fields=['bien_qr_code'], name='mobile_camb_bien_qr_6f033f_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiooffline',
            index=models.Index(fields=['estado_sync'], name='mobile_camb_estado__3cd251_idx'),
        ),
    ]
