# Generated by Django 5.2.7 on 2025-11-04 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=True)),
                ('plantilla_email', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='AlertaDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('meses_anticipacion', models.IntegerField(default=6, help_text='Meses de anticipación para la alerta')),
                ('vida_util_anos', models.IntegerField(default=10, help_text='Vida útil en años')),
                ('grupos_catalogo', models.JSONField(blank=True, default=list, help_text='Grupos de catálogo a incluir')),
                ('oficinas', models.JSONField(blank=True, default=list, help_text='Oficinas a incluir')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios_notificar', models.ManyToManyField(blank=True, help_text='Usuarios a notificar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Depreciación',
                'verbose_name_plural': 'Alertas de Depreciación',
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_bien', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('EQUIPO', 'Equipo'), ('MOBILIARIO', 'Mobiliario'), ('TODOS', 'Todos los tipos')], default='TODOS', max_length=20)),
                ('dias_anticipacion', models.IntegerField(default=30, help_text='Días de anticipación para la alerta')),
                ('frecuencia_meses', models.IntegerField(default=6, help_text='Frecuencia de mantenimiento en meses')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios_notificar', models.ManyToManyField(blank=True, help_text='Usuarios a notificar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('datos_contexto', models.JSONField(blank=True, default=dict)),
                ('url_accion', models.URLField(blank=True, help_text='URL para acción relacionada')),
                ('fecha_programada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.IntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notificaciones.notificacion')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historiales de Notificaciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=True)),
                ('frecuencia_dias', models.IntegerField(default=1, help_text='Frecuencia en días para notificaciones recurrentes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_notificacion', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'unique_together': {('usuario', 'tipo_notificacion')},
            },
        ),
    ]
