# Generated by Django 5.2.7 on 2025-11-05 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('oficinas', 'Oficinas'), ('bienes', 'Bienes Patrimoniales'), ('catalogo', 'Catálogo'), ('core', 'Sistema')], help_text='Módulo al que aplica la configuración', max_length=50, unique=True, verbose_name='Módulo')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Número de días que los elementos permanecen en papelera antes de eliminación automática', verbose_name='Días de retención')),
                ('auto_delete_enabled', models.BooleanField(default=True, help_text='Si está habilitada la eliminación automática por tiempo', verbose_name='Eliminación automática habilitada')),
                ('warning_days_before', models.PositiveIntegerField(default=7, help_text='Días antes de eliminación automática para enviar advertencia', verbose_name='Días de advertencia')),
                ('final_warning_days_before', models.PositiveIntegerField(default=1, help_text='Días antes de eliminación automática para enviar advertencia final', verbose_name='Días de advertencia final')),
                ('can_restore_own', models.BooleanField(default=True, help_text='Los usuarios pueden restaurar elementos que ellos eliminaron', verbose_name='Puede restaurar propios')),
                ('can_restore_others', models.BooleanField(default=False, help_text='Los usuarios pueden restaurar elementos eliminados por otros', verbose_name='Puede restaurar de otros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de Papelera',
                'verbose_name_plural': 'Configuraciones de Papelera',
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID del objeto eliminado', verbose_name='ID del objeto')),
                ('object_repr', models.CharField(help_text='Representación en texto del objeto eliminado', max_length=500, verbose_name='Representación del objeto')),
                ('module_name', models.CharField(help_text='Módulo al que pertenece el objeto (oficinas, bienes, catalogo)', max_length=100, verbose_name='Nombre del módulo')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se eliminó el objeto', verbose_name='Fecha de eliminación')),
                ('deletion_reason', models.TextField(blank=True, help_text='Razón por la cual se eliminó el objeto', verbose_name='Motivo de eliminación')),
                ('restored_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se restauró el objeto', null=True, verbose_name='Fecha de restauración')),
                ('auto_delete_at', models.DateTimeField(help_text='Fecha y hora en que se eliminará automáticamente', verbose_name='Eliminación automática')),
                ('original_data', models.JSONField(blank=True, help_text='Snapshot de los datos del objeto antes de eliminación', null=True, verbose_name='Datos originales')),
                ('content_type', models.ForeignKey(help_text='Tipo de modelo del objeto eliminado', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('deleted_by', models.ForeignKey(help_text='Usuario que eliminó el objeto', on_delete=django.db.models.deletion.PROTECT, related_name='recycle_bin_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('restored_by', models.ForeignKey(blank=True, help_text='Usuario que restauró el objeto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recycle_bin_restorations', to=settings.AUTH_USER_MODEL, verbose_name='Restaurado por')),
            ],
            options={
                'verbose_name': 'Elemento en Papelera',
                'verbose_name_plural': 'Elementos en Papelera',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='recycle_deleted_at_idx'), models.Index(fields=['deleted_by'], name='recycle_deleted_by_idx'), models.Index(fields=['auto_delete_at'], name='recycle_auto_delete_idx'), models.Index(fields=['module_name'], name='recycle_module_name_idx'), models.Index(fields=['content_type', 'object_id'], name='recycle_content_idx'), models.Index(fields=['restored_at'], name='recycle_restored_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('restored_at__isnull', True)), fields=('content_type', 'object_id'), name='unique_active_recycle_entry')],
            },
        ),
    ]
