# Generated by Django 5.2.7 on 2025-11-09 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_recycle_bin_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del intento', verbose_name='Fecha del intento')),
                ('success', models.BooleanField(default=False, help_text='Si el intento fue exitoso', verbose_name='Exitoso')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó el intento', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador', verbose_name='User Agent')),
                ('recycle_bin_entry_id', models.PositiveIntegerField(blank=True, help_text='ID de la entrada de RecycleBin que se intentó eliminar', null=True, verbose_name='ID de entrada en papelera')),
                ('user', models.ForeignKey(help_text='Usuario que intentó usar el código', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de Código de Seguridad',
                'verbose_name_plural': 'Intentos de Código de Seguridad',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', 'attempted_at'], name='security_user_time_idx'), models.Index(fields=['attempted_at'], name='security_time_idx')],
            },
        ),
    ]
