# Generated by Django 5.2.7 on 2025-11-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Código único del catálogo SBN (ej: 04220001)', max_length=20, unique=True, verbose_name='Código de Catálogo')),
                ('denominacion', models.CharField(help_text='Nombre oficial del bien según catálogo SBN', max_length=500, unique=True, verbose_name='Denominación del Bien')),
                ('grupo', models.CharField(help_text='Código y descripción del grupo (ej: 04 AGRICOLA Y PESQUERO)', max_length=50, verbose_name='Grupo')),
                ('clase', models.CharField(help_text='Código y descripción de la clase (ej: 22 EQUIPO)', max_length=50, verbose_name='Clase')),
                ('resolucion', models.CharField(help_text='Resolución que aprueba el bien (ej: 011-2019/SBN)', max_length=100, verbose_name='Resolución')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EXCLUIDO', 'Excluido')], default='ACTIVO', help_text='Estado del bien en el catálogo', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='catalogo_ca_codigo_aaa4ec_idx'), models.Index(fields=['denominacion'], name='catalogo_ca_denomin_ddd024_idx'), models.Index(fields=['grupo'], name='catalogo_ca_grupo_beb16b_idx'), models.Index(fields=['clase'], name='catalogo_ca_clase_ca844c_idx'), models.Index(fields=['estado'], name='catalogo_ca_estado_60b799_idx')],
            },
        ),
    ]
