# Generated by Django 5.1.3 on 2025-11-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_importobservation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importobservation',
            new_name='catalogo_im_modulo_67af50_idx',
            old_name='catalogo_im_modulo_f8e9c5_idx',
        ),
        migrations.RenameIndex(
            model_name='importobservation',
            new_name='catalogo_im_tipo_68db9f_idx',
            old_name='catalogo_im_tipo_se_4a2b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='importobservation',
            new_name='catalogo_im_resuelt_79fcd8_idx',
            old_name='catalogo_im_resuelto_3d4e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='importobservation',
            new_name='catalogo_im_usuario_140ddf_idx',
            old_name='catalogo_im_usuario_5f6g3h_idx',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='denominacion',
            field=models.CharField(help_text='Nombre oficial del bien según catálogo SBN', max_length=500, verbose_name='Denominación del Bien'),
        ),
    ]
