# Generated by Django 5.2.7 on 2025-11-04 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Código único de la oficina (ej: DIR-001, ADM-002)', max_length=20, unique=True, verbose_name='Código de Oficina')),
                ('nombre', models.CharField(help_text='Nombre completo de la oficina', max_length=200, verbose_name='Nombre de la Oficina')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la oficina y sus funciones', verbose_name='Descripción')),
                ('responsable', models.CharField(help_text='Nombre del responsable de la oficina', max_length=200, verbose_name='Responsable')),
                ('cargo_responsable', models.CharField(blank=True, help_text='Cargo o puesto del responsable', max_length=200, verbose_name='Cargo del Responsable')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de la oficina', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de la oficina', max_length=254, verbose_name='Email')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física de la oficina (piso, edificio, etc.)', max_length=300, verbose_name='Ubicación')),
                ('estado', models.BooleanField(default=True, help_text='Indica si la oficina está activa', verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='oficinas_of_codigo_c172bd_idx'), models.Index(fields=['nombre'], name='oficinas_of_nombre_01e17d_idx'), models.Index(fields=['estado'], name='oficinas_of_estado_14b0c6_idx'), models.Index(fields=['responsable'], name='oficinas_of_respons_67078b_idx')],
            },
        ),
    ]
