# Generated by Django 5.2.7 on 2025-11-05 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficinas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficinas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.CreateModel(
            name='HistorialOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ACTIVAR', 'Activación'), ('DESACTIVAR', 'Desactivación'), ('IMPORTAR', 'Importación')], max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior de la oficina', null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo de la oficina', null=True, verbose_name='Datos nuevos')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios adicionales sobre el cambio', verbose_name='Observaciones')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='oficinas.oficina', verbose_name='Oficina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Oficina',
                'verbose_name_plural': 'Historiales de Oficinas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['oficina', '-fecha'], name='oficinas_hi_oficina_04fe98_idx'), models.Index(fields=['usuario', '-fecha'], name='oficinas_hi_usuario_285b1b_idx'), models.Index(fields=['accion', '-fecha'], name='oficinas_hi_accion_cf1c83_idx')],
            },
        ),
    ]
