# Generated by Django 5.2.7 on 2025-11-05 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0002_alter_oficina_created_by_alter_oficina_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Razón por la cual se eliminó el registro', verbose_name='Motivo de eliminación'),
        ),
    ]
