# Generated by Django 5.2.7 on 2025-11-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo para la configuración de filtros', max_length=200, verbose_name='Nombre de la Configuración')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de los filtros aplicados', verbose_name='Descripción')),
                ('es_publica', models.BooleanField(default=False, help_text='Si está marcado, otros usuarios pueden usar esta configuración', verbose_name='Es Pública')),
                ('oficinas', models.JSONField(blank=True, default=list, help_text='Lista de IDs de oficinas seleccionadas', verbose_name='Oficinas')),
                ('estados_bien', models.JSONField(blank=True, default=list, help_text='Lista de estados seleccionados (N, B, R, M, E, C)', verbose_name='Estados del Bien')),
                ('grupos_catalogo', models.JSONField(blank=True, default=list, help_text='Lista de grupos de catálogo seleccionados', verbose_name='Grupos de Catálogo')),
                ('clases_catalogo', models.JSONField(blank=True, default=list, help_text='Lista de clases de catálogo seleccionadas', verbose_name='Clases de Catálogo')),
                ('marcas', models.JSONField(blank=True, default=list, help_text='Lista de marcas seleccionadas', verbose_name='Marcas')),
                ('modelos', models.JSONField(blank=True, default=list, help_text='Lista de modelos seleccionados', verbose_name='Modelos')),
                ('fecha_adquisicion_desde', models.DateField(blank=True, help_text='Fecha de inicio para filtro de adquisición', null=True, verbose_name='Fecha Adquisición Desde')),
                ('fecha_adquisicion_hasta', models.DateField(blank=True, help_text='Fecha de fin para filtro de adquisición', null=True, verbose_name='Fecha Adquisición Hasta')),
                ('fecha_registro_desde', models.DateField(blank=True, help_text='Fecha de inicio para filtro de registro', null=True, verbose_name='Fecha Registro Desde')),
                ('fecha_registro_hasta', models.DateField(blank=True, help_text='Fecha de fin para filtro de registro', null=True, verbose_name='Fecha Registro Hasta')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo de adquisición', max_digits=12, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo de adquisición', max_digits=12, null=True, verbose_name='Valor Máximo')),
                ('codigo_patrimonial', models.CharField(blank=True, help_text='Filtro por código patrimonial (búsqueda parcial)', max_length=100, verbose_name='Código Patrimonial')),
                ('denominacion', models.CharField(blank=True, help_text='Filtro por denominación del bien (búsqueda parcial)', max_length=200, verbose_name='Denominación')),
                ('serie', models.CharField(blank=True, help_text='Filtro por número de serie (búsqueda parcial)', max_length=100, verbose_name='Serie')),
                ('placa', models.CharField(blank=True, help_text='Filtro por placa (búsqueda parcial)', max_length=20, verbose_name='Placa')),
                ('operador_principal', models.CharField(choices=[('AND', 'Y (AND)'), ('OR', 'O (OR)')], default='AND', help_text='Operador lógico principal para combinar filtros', max_length=3, verbose_name='Operador Principal')),
                ('configuracion_avanzada', models.JSONField(blank=True, default=dict, help_text='Configuración JSON para filtros complejos', verbose_name='Configuración Avanzada')),
                ('veces_usado', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha usado esta configuración', verbose_name='Veces Usado')),
                ('ultima_vez_usado', models.DateTimeField(blank=True, help_text='Fecha y hora del último uso', null=True, verbose_name='Última Vez Usado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que creó la configuración', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Filtro',
                'verbose_name_plural': 'Configuraciones de Filtros',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('INVENTARIO', 'Inventario General'), ('ESTADISTICO', 'Reporte Estadístico'), ('EJECUTIVO', 'Reporte Ejecutivo'), ('STICKERS', 'Plantilla de Stickers'), ('PERSONALIZADO', 'Reporte Personalizado')], help_text='Tipo de reporte generado', max_length=20, verbose_name='Tipo de Reporte')),
                ('formato', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('PDF', 'PDF'), ('CSV', 'CSV'), ('ZPL', 'Plantilla ZPL')], help_text='Formato de exportación del reporte', max_length=10, verbose_name='Formato')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros utilizados para generar el reporte', verbose_name='Parámetros')),
                ('estado', models.CharField(choices=[('GENERANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('EXPIRADO', 'Expirado')], default='GENERANDO', help_text='Estado actual del reporte', max_length=15, verbose_name='Estado')),
                ('total_registros', models.PositiveIntegerField(blank=True, help_text='Número total de registros en el reporte', null=True, verbose_name='Total de Registros')),
                ('archivo_generado', models.FileField(blank=True, help_text='Archivo del reporte generado', upload_to='reportes/', verbose_name='Archivo Generado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de generación', verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha y hora de completado', null=True, verbose_name='Fecha de Completado')),
                ('tiempo_procesamiento', models.DurationField(blank=True, help_text='Tiempo total de procesamiento', null=True, verbose_name='Tiempo de Procesamiento')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el reporte falló', verbose_name='Mensaje de Error')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de expiración del archivo', null=True, verbose_name='Fecha de Expiración')),
                ('configuracion_filtro', models.ForeignKey(blank=True, help_text='Configuración de filtros utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.configuracionfiltro', verbose_name='Configuración de Filtro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que generó el reporte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='configuracionfiltro',
            index=models.Index(fields=['usuario'], name='reportes_co_usuario_8dc778_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionfiltro',
            index=models.Index(fields=['es_publica'], name='reportes_co_es_publ_6872b3_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionfiltro',
            index=models.Index(fields=['nombre'], name='reportes_co_nombre_921219_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionfiltro',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['usuario'], name='reportes_re_usuario_bfbc20_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['tipo_reporte'], name='reportes_re_tipo_re_f0f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['estado'], name='reportes_re_estado_077bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='reportegenerado',
            index=models.Index(fields=['fecha_inicio'], name='reportes_re_fecha_i_632cff_idx'),
        ),
    ]
